name: CI-SDK

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  SDK:
    runs-on: macOS-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Switch to Xcode 11.4
      run: sudo xcode-select --switch /Applications/Xcode_11.4.app

    # Generate xcode project
    - name: Generate xcodeproj
      run: swift package generate-xcodeproj --xcconfig-overrides Sources/Config.xcconfig

    # Compile project and run tests
    - name: Compile and run tests
      run: fastlane scan

  SampleApp:
    runs-on: macOS-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Switch to Xcode 11.4
      run: sudo xcode-select --switch /Applications/Xcode_11.4.app

    # Compile sample app
    - name: Compile and run tests
      run: fastlane gym --project SampleApp/STARSampleApp.xcodeproj --scheme "Debug" --skip_package_ipa true

