name: distribute

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  appcenter:
    runs-on: macOS-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Switch to Xcode 11.4
      run: sudo xcode-select --switch /Applications/Xcode_11.4.app

    - name: Trust Github
      run: ssh-keyscan github.com >> ~/.ssh/known_hosts
      
    - name: Run fastlane build
      env:
        MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASS }}
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
        TEAM_ID: ${{ secrets.TEAM_ID }}
        APPCENTER_APP_NAME: ${{ secrets.APPCENTER_APP_NAME }}
        APPCENTER_OWNER_NAME:  ${{ secrets.APPCENTER_OWNER_NAME }}
        APPCENTER_API_TOKEN: ${{ secrets.APPCENTER_API_TOKEN }}
      run: |
        fastlane distribute --verbose
      working-directory: SampleApp

